function createfigure(X1, Y1, Z1, S1, C1)
%CREATEFIGURE(X1, Y1, Z1, S1, C1)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c

%  Auto-generated by MATLAB on 27-Aug-2015 21:10:22

% Create figure
figure1 = figure;
colormap('prism');

% Create axes
axes1 = axes('Parent',figure1,'Color',[0 0 0],'CLim',[3 5]);
%% Uncomment the following line to preserve the X-limits of the axes
%xlim(axes1,[0 1000]);
%% Uncomment the following line to preserve the Y-limits of the axes
%ylim(axes1,[0 1000]);
view(axes1,[90 90]);
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'MarkerFaceColor','flat','MarkerEdgeColor','none');