function createfigure3(X1, Y1, Z1, Vertices1, VertexNormals1, Faces1, X2, Y2, Z2)
%CREATEFIGURE4(X1, Y1, Z1, S1, C1, VERTICES1, VERTEXNORMALS1, FACES1, X2, Y2, Z2, S2, C2)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c
%  VERTICES1:  patch vertices
%  VERTEXNORMALS1:  patch vertexnormals
%  FACES1:  patch faces
%  X2:  scatter3 x
%  Y2:  scatter3 y
%  Z2:  scatter3 z
%  S2:  scatter3 s
%  C2:  scatter3 c

%  Auto-generated by MATLAB on 03-Dec-2015 17:42:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Color',[0 0 0],...
    'ZColor',[0.501960813999176 0.501960813999176 0.501960813999176],...
    'YColor',[0.501960813999176 0.501960813999176 0.501960813999176],...
    'XColor',[0.501960813999176 0.501960813999176 0.501960813999176],...
    'DataAspectRatio',[1 1 1]);
view(axes1,[-70.5 40]);
box(axes1,'on');
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,50,'MarkerEdgeColor',[1 0 0],'Marker','.');

% Create patch
patch('Parent',axes1,'FaceLighting','gouraud','FaceAlpha',0.5,...
    'Vertices',Vertices1,...
    'VertexNormals',VertexNormals1,...
    'Faces',Faces1,...
    'FaceColor',[0 0 1],...
    'EdgeColor','none');

% Create light
light('Parent',axes1,...
    'Position',[244.817067307074 -733.002902326085 1235.67614387691],...
    'Style','local');

% Create scatter3
scatter3(X2,Y2,Z2,50,'MarkerEdgeColor',[1 1 0],'Marker','.');

