function [imgfillmask] = segmentNuclei(im, level)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(IM) segments image IM using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 01-Dec-2015
%----------------------------------------------------


% Initialize segmentation with given threshold
 %mask = im>0.20585;

% Initialize segmentation with Otsu's threshold
% Uncomment below to let auto threshold work.
% This is a bad idea for the stacks since the ones on the top that should
% be weak greys will get blown up and selected. If you want this calculate
% the threshold for the entire stack first, outside this function and then
% use that here as an argument above
%level = graythresh(im);
mask = im2bw(im,level);

% Evolve segmentation
BW = activecontour(im, mask, 100, 'Chan-Vese','SmoothFactor',1.5,'ContractionBias',0.5);

% Suppress components connected to image border
BW = imclearborder(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Filter components by area, uncomment if desired.
% The nuclei in a mid stack is between 8000 and 14000 or so
% Good limits may be [2500 30000]
BW = bwareafilt(BW, [2500 30000]);

% Form masked image from input image and segmented image.
maskedImage = im;
maskedImage(~BW) = 0;

% Fill holes in greyscale dapi
imgfillmask = imfill(maskedImage, 'holes');
end
