function [imgfillmask] = segmentImageBen(im)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(IM) segments image IM using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 22-Feb-2016
%----------------------------------------------------


% Initialize segmentation with Otsu's threshold
level = graythresh(im);
mask = im2bw(im,level);

% Evolve segmentation
BW = activecontour(im, mask, 100, 'Chan-Vese');

% Suppress components connected to image border
BW = imclearborder(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Filter components by area
BW = bwareafilt(BW, [5 300]);

% Form masked image from input image and segmented image.
maskedImage = im;
maskedImage(~BW) = 0;
imgfillmask = imfill(maskedImage, 'holes');
end
